package com.viewsonic.classswift.api

import com.viewsonic.classswift.api.body.CreateQuizCollectionFolderBody
import com.viewsonic.classswift.api.response.CreateQuizCollectionFolderResponse
import com.viewsonic.classswift.api.response.QuizzesInCollectionFolderResponse
import com.viewsonic.classswift.api.response.SourceTypeMappingResponse
import com.viewsonic.classswift.api.response.data.QuizCollectionFolder
import com.viewsonic.classswift.api.retrofit.ApiResponse
import retrofit2.http.Body
import retrofit2.http.GET
import retrofit2.http.Header
import retrofit2.http.POST
import retrofit2.http.Path
import retrofit2.http.Query

interface QuizCollectionApiService {

    @POST("/api/v3/quizzes/collection/folder")
    suspend fun createQuizCollectionFolder(
        @Header("Authorization") token: String,
        @Body createQuizCollectionFolderBody: CreateQuizCollectionFolderBody
    ): ApiResponse<CreateQuizCollectionFolderResponse>

    @GET("/api/v3/quizzes/collection/folder")
    suspend fun getQuizCollectionFolders(
        @Header("Authorization") token: String,
        @Query("org_id") orgId: String,
    ): ApiResponse<List<QuizCollectionFolder>>

    @GET("/api/v3/quizzes/collection/origin/source_type")
    suspend fun getSourceTypeMapping(
        @Header("Authorization") token: String
    ): ApiResponse<SourceTypeMappingResponse>

    @GET("/api/v3/quizzes/collection/folder/{folder_id}/quizzes")
    suspend fun getQuizzesInCollectionFolder(
        @Header("Authorization") token: String,
        @Path("folder_id") folderId: String,

        /**
         * The current page number to retrieve.
         * Defaults to 1 on the server.
         */
        @Query("page") page: Int = 1,

        /**
         * The number of items to include per page.
         * Defaults to 10 on the server.
         */
        @Query("per_page") perPage: Int = 24,

        /**
         * Filters quizzes by their origin.
         *
         * Possible values:
         * - "AI": Returns quizzes generated by AI.
         * - "CONTENT": Returns quizzes created by the authenticated user.
         * - null: Returns all quizzes, regardless of origin.
         */
        @Query("origin") origin: String? = null,
        @Query("source_types") sourceTypes: List<String>? = null,

        @Query("country") country: String = "",
        @Query("subject") subject: String = "",

        /**
         * When true, only return quizzes where at least one option in option_list has is_answer = true.
         * When false or null, no filtering is applied.
         */
        @Query("has_answer") hasAnswer: Boolean = true,

        /**
         * Filters quizzes by their quiz type.
         *
         * Possible values:
         * - "TRUE_FALSE", "SINGLE_SELECT", "MULTIPLE_SELECT", "RECORD", "SHORT_ANSWER", "SINGLE_POLL", "MULTIPLE_POLL"
         * - null: Returns all quizzes, regardless of quiz type.
         *
         * To filter multiple quiz types, use a comma-separated string.
         * Example: "TRUE_FALSE,SINGLE_SELECT"
         */
        @Query("quiz_type") quizType: String = "",

        /**
         * Filters quizzes by their creation date within the last specified number of days.
         *
         * Possible values:
         * - 0: Returns all quizzes, regardless of creation time.
         * - x > 0: Returns quizzes created within the last x days.
         */
        @Query("created_at") createdAt: Int = 0,

        /**
         * Sorts the quizzes by the specified method.
         * Defaults to "PIN_AND_CREATED_AT" on the server.
         *
         * Possible values:
         * - "QUIZ_TYPE"
         * - "PIN_AND_CREATED_AT"
         */
        @Query("order_by") orderBy: String = "PIN_AND_CREATED_AT",
    ): ApiResponse<QuizzesInCollectionFolderResponse>

}