package com.viewsonic.classswift.windowframework.core.enums

enum class WindowTag {
    NONE,
    CROP_IMAGE,
    MVB_CROP_IMAGE,
    DEFAULT,
    TOOLBAR,
    CS_NORMAL_DIALOG,
    CS_SYSTEM_DIALOG,
    FORCE_LOGOUT_DIALOG,
    CS_SELECT_ORG,
    CLASS_MANAGEMENT_MENU, // aka IRS (Interactive Response System).
    TOOLS_MENU, // aka IRS (Interactive Response System).
    SETTING_MENU, // aka IRS (Interactive Response System).
    QUIZ_MENU, // aka IRS (Interactive Response System).
    UPGRADE_PROMPT,
    COMING_SOON_PROMPT,
    CS_SELECT_MY_CLASS,
    CS_SELECT_ORG_AND_CLASS,
    STUDENT_MANAGEMENT,
    JOIN_CLASS,
    WINDOW_UPCOMING_MAINTENANCE,
    WINDOW_UPCOMING_MAINTENANCE_CORNER_PROMPT,
    WINDOW_UNDER_MAINTENANCE,
    WINDOW_QUIZ_COLLECTION,
    WINDOW_MVB_QUIZ_COLLECTION,
    WINDOW_TOAST,
    WINDOW_TUTORIAL,
    WINDOW_IN_APP_TUTORIAL,
    MVB_TRUE_FALSE_EDIT_QUIZ,
    TRUE_FALSE_EDIT_QUIZ,
    TRUE_FALSE_START_QUIZ,
    MVB_MULTIPLE_CHOICE_EDIT_QUIZ,
    MULTIPLE_CHOICE_EDIT_QUIZ,
    MULTIPLE_CHOICE_START_QUIZ,
    SHORT_ANSWER_EDIT_QUIZ,
    SHORT_ANSWER_START_QUIZ,
    MVB_AUDIO_EDIT_QUIZ,
    AUDIO_EDIT_QUIZ,
    AUDIO_START_QUIZ,
    MVB_POLL_EDIT_QUIZ,
    POLL_EDIT_QUIZ,
    POLL_START_QUIZ,
    TIMER_TOOL,
    RANDOM_DRAW_TOOL,
    BUZZER_TOOL,
    MVB_SPINNER,
    SPINNER_TOOL,
    SETTING_WINDOW,
    PUSH_RESPOND,
    WINDOW_TEXT_TRUE_FALSE_START_QUIZ,
    WINDOW_TEXT_MULTIPLE_CHOICE_START_QUIZ,
    WINDOW_TEXT_SHORT_ANSWER_START_QUIZ,
    LEADERBOARD_WINDOW,
    BATCH_START_QUIZ,
    BATCH_QUIZ_RESULT,
    MVB_TRUE_FALSE_START_QUIZ,
    MVB_TEXT_TRUE_FALSE_START_QUIZ,
    MVB_MULTIPLE_CHOICE_START_QUIZ,
    MVB_POLL_START_QUIZ,
    MVB_AUDIO_START_QUIZ,
    MVB_SHORT_ANSWER_START_QUIZ,
    MVB_TEXT_SHORT_ANSWER_START_QUIZ,
    MVB_SHORT_ANSWER_EDIT_QUIZ,
    MVB_SKETCH_RESPONSE_EDIT_QUIZ,
    MVB_SKETCH_RESPONSE_START_QUIZ;


    companion object {
        fun getSubWindowTagList() = listOf(
            CLASS_MANAGEMENT_MENU,
            TOOLS_MENU,
            SETTING_MENU,
            QUIZ_MENU,
            UPGRADE_PROMPT,
            COMING_SOON_PROMPT
        )

        fun getImageQuizEditWindowTagList() = listOf(
            TRUE_FALSE_EDIT_QUIZ,
            MVB_TRUE_FALSE_EDIT_QUIZ,
            MULTIPLE_CHOICE_EDIT_QUIZ,
            MVB_MULTIPLE_CHOICE_EDIT_QUIZ,
            SHORT_ANSWER_EDIT_QUIZ,
            MVB_AUDIO_EDIT_QUIZ,
            MVB_SHORT_ANSWER_EDIT_QUIZ,
            AUDIO_EDIT_QUIZ,
            MVB_POLL_EDIT_QUIZ,
            POLL_EDIT_QUIZ,
            MVB_SKETCH_RESPONSE_EDIT_QUIZ,
        )

        // Always on Top Window
        fun getFirstLevelWindowTagList() = listOf(FORCE_LOGOUT_DIALOG, CS_SYSTEM_DIALOG)

        fun isSubWindowTag(tag: WindowTag) = getSubWindowTagList().contains(tag)
    }
}
