name: 'Security Full Scan'

on:
  push:
    branches:
      - develop
      - master
      - main
  schedule:
    - cron: '25 9 * * *'
  workflow_dispatch:

jobs:
  scan:
    uses: VSX-ViewSonic/edu-security-lab-va/.github/workflows/workflow-scan-full.yml@main
    with:
      product_name: "edu/classswift/ragdoll-cat"
